### TEST 1: Register new user
POST http://localhost:8081/api/auth/register
Content-Type: application/json

{
  "name": "Muna Afifah",
  "email": "muna@example.com",
  "password": "password123"
}

### TEST 2: Login with correct credentials
POST http://localhost:8081/api/auth/login
Content-Type: application/json

{
  "email": "muna@example.com",
  "password": "password123"
}

### TEST 3: Register with duplicate email
POST http://localhost:8081/api/auth/register
Content-Type: application/json

{
  "name": "Duplicate User",
  "email": "muna@example.com",
  "password": "password123"
}

### TEST 4: Login with wrong password
POST http://localhost:8081/api/auth/login
Content-Type: application/json

{
  "email": "muna@example.com",
  "password": "wrongpassword"
}

### TEST 5: Get tickets without token (expect 401)
GET http://localhost:8081/api/tickets

### TEST 6: Login as USER to get a token
POST http://localhost:8081/api/auth/login
Content-Type: application/json

{
  "email": "muna@example.com",
  "password": "password123"
}

### TEST 7: Get tickets with USER token (expect 200) - paste token from TEST 6
GET http://localhost:8081/api/tickets
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtdW5hQGV4YW1wbGUuY29tIiwicm9sZSI6IlVTRVIiLCJpc3MiOiJzdXBwb3J0LWRlc2stYXBpIiwibmFtZSI6Ik11bmEgQWZpZmFoIiwiZXhwIjoxNzg0ODIyMjQ1LCJpYXQiOjE3ODQ4MTg2NDUsInVzZXJJZCI6IjZhNjBjZGIwZjdkNGQ5OGM1MTMzZGRiNyJ9.oqVvpH_JPkceAcPsqod6aWDt6f1qYwdORngt8PoLyvY

### TEST 8: Create ticket with USER token (expect 403) - paste token from TEST 6
POST http://localhost:8081/api/tickets
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtdW5hQGV4YW1wbGUuY29tIiwicm9sZSI6IlVTRVIiLCJpc3MiOiJzdXBwb3J0LWRlc2stYXBpIiwibmFtZSI6Ik11bmEgQWZpZmFoIiwiZXhwIjoxNzg0ODIyMjQ1LCJpYXQiOjE3ODQ4MTg2NDUsInVzZXJJZCI6IjZhNjBjZGIwZjdkNGQ5OGM1MTMzZGRiNyJ9.oqVvpH_JPkceAcPsqod6aWDt6f1qYwdORngt8PoLyvY

{
  "title": "Test ticket",
  "description": "Testing role restriction",
  "category": "Other",
  "priority": "LOW",
  "createdBy": "muna@example.com"
}

### EXERCISE 5 COVERS ONLY UNTIL TEST 8. THE FOLLOWING TESTS ARE OPTIONAL AND FOR EXTRA PRACTICE.

### TEST 9: Login as ADMIN
POST http://localhost:8081/api/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "Admin@12345"
}

### TEST 10: Create ticket with ADMIN token (expect 201) - paste token from TEST 9
POST http://localhost:8081/api/tickets
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJBRE1JTiIsImlzcyI6InN1cHBvcnQtZGVzay1hcGkiLCJuYW1lIjoiQWRtaW4gVXNlciIsImV4cCI6MTc4NDgyMjg1MywiaWF0IjoxNzg0ODE5MjUzLCJ1c2VySWQiOiI2YTYyMmUxZTJiYTFkYjcxN2QyMWUwYTIifQ.FxTDGoSp4w_QenLR0mQ5LYtIpCwuNMDXo_wQ2vHjbsc
Content-Type: application/json

{
  "title": "Server room AC not working",
  "description": "Server room temperature rising, AC unit not responding.",
  "category": "Facilities",
  "priority": "HIGH",
  "createdBy": "admin@example.com"
}